swagger: '2.0'
info:
  title: WSO2 API Manager - Gateway
  version: v0.9
  description: This document specifies a **RESTful API** for WSO2 **API Manager** - Gateway
  contact:
    name: WSO2
    url: 'https://wso2.com/api-manager/'
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/am/gateway/v0.9
consumes:
  - application/json
produces:
  - application/json
paths:
  /api-logging:
    post:
      summary: |
        POST logging data of the API with its context template and version.
      description: |
        This operation enables you to provide the API context template (context/version) with the log level (headers, body, or all). You should ***either provide a payload or context, and the logLevel as the query parameters*** with this API request.
      parameters:
        - name: Payload
          description: |
            The context and the logLevel can be provided as a payload. This is useful if you want to enable logs for multiple APIs at once.
          required: false
          in: body
          schema:
            $ref: '#/definitions/APIList'
        - name: context
          in: query
          description: |
            The API context (context/version e.g., pizzashack/1.0.0)
          required: false
          type: string
        - name: logLevel
          in: query
          description: |
            The logLevel of the API. "all","headers" or "body"
          required: false
          type: string
          enum:
            - all
            - headers
            - body
      responses:
        '200':
          description: 'Successfully enabled the logs for the API'
          schema:
            $ref: '#/definitions/APIList'
        '404':
          description: |
            Not Found.
            Requested API resource or external store IDs not found.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error while configuring the API to be logged.
          schema:
            $ref: '#/definitions/Error'
    get:
      responses:
        '200':
          description: 'Logs enabled API details'
          schema:
            $ref: '#/definitions/APIList'
        '404':
          description: |
            Not Found.
            Requested API resource or external store IDs not found.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error while retrieving API data to be logged.
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: context
          in: query
          description: |
            The API context with the version (e.g., pizzashack/1.0.0). If this is not provided, then it will retrieve details of all the APIs that have logs enabled with log levels.
          required: false
          type: string
    delete:
      responses:
        '204':
          description: 'Successfully deleted'
        '404':
          description: |
            Not Found.
            Requested API context is not found.
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal server error while deleting API details.
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: context
          in: query
          required: false
          type: string
          description: |
            API context with the version (e.g., pizzashack/1.0.0). If this is not provided, all the API details will be deleted.
definitions:
  APIList:
    title: apis
    properties:
      apis:
        type: array
        items:
          $ref: '#/definitions/API'
  API:
    title: API Info object with log details
    properties:
      context:
        type: string
        example: pizashack/v1.0.0
      logLevel:
        type: string
        example: all
  Error:
    title: Error object returned with 4XX HTTP Status
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
        description: Error message.
      description:
        type: string
        description: |
          A detailed description of the error message.
      moreInfo:
        type: string
        description: |
          Preferably an URL with more details about the error.
      error:
        type: array
        description: |
          If there is more than one error, list them out.
          For example, list out validation errors by each field.
        items:
          $ref: '#/definitions/ErrorListItem'
  ErrorListItem:
    title: Description of individual errors that may have occurred during a request.
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
        description: |
          A description of the individual errors that occurred.
      description:
        type: string
        description: |
          A detailed description of the error message.
